import { DiscountCode, SubscriptionPlan } from "./types";

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: "basic",
    name: "Basic",
    price: 20,
    annualPrice: 18,
    currency: "KWD",
    reachLimit: 500,
    memberships: false,
    features: [
      "Marketing reach: 500 recipients/month",
      "Courses, Live sessions, Programs: Unlimited",
      "Memberships: Not included",
      "Content Studio: Full access",
      "Analytics: Business, Audience, Products",
      "Email, WhatsApp, Telegram channels",
      "Free weekly & monthly payouts",
      "Immediate payout: 1 KWD per request",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: 35,
    annualPrice: 28,
    currency: "KWD",
    reachLimit: 5000,
    memberships: true,
    isPopular: true,
    features: [
      "Marketing reach: 5,000 recipients/month",
      "Courses, Live sessions, Programs: Unlimited",
      "Memberships: Included",
      "Content Studio: Full access",
      "Analytics: Business, Audience, Product insights",
      "Email, WhatsApp, Telegram channels",
      "Free weekly & monthly payouts",
      "Immediate payout: 1 KWD per request",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 85,
    annualPrice: 70,
    currency: "KWD",
    reachLimit: 50000,
    memberships: true,
    features: [
      "Marketing reach: 50,000 recipients/month",
      "Courses, Live sessions, Programs: Unlimited",
      "Memberships: Included",
      "Content Studio: Full access",
      "Analytics: Full analytics depth",
      "All channels (Instagram, SMS, Push coming soon)",
      "Free weekly & monthly payouts",
      "Immediate payout: 1 KWD per request",
    ],
  },
];

export const mockDiscountCodes: DiscountCode[] = [
  {
    id: "1",
    code: "SUMMER25",
    type: "percentage",
    value: 25,
    totalUses: 45,
    maxUses: 100,
    perCustomerLimit: 1,
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-08-31"),
    productIds: "all",
    status: "active",
    usages: [
      { userId: "u1", userName: "Ahmed Hassan", usedAt: new Date("2025-06-15"), orderAmount: 75 },
      { userId: "u2", userName: "Sara Ali", usedAt: new Date("2025-06-18"), orderAmount: 120 },
      { userId: "u3", userName: "Omar Khalil", usedAt: new Date("2025-06-20"), orderAmount: 50 },
    ],
    totalRevenue: 3375,
    createdAt: new Date("2025-05-28"),
  },
  {
    id: "2",
    code: "LAUNCH10",
    type: "fixed",
    value: 10,
    totalUses: 28,
    maxUses: 50,
    perCustomerLimit: 2,
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-12-31"),
    productIds: ["prod-1", "prod-2"],
    status: "active",
    usages: [
      { userId: "u4", userName: "Fatima Noor", usedAt: new Date("2025-01-10"), orderAmount: 60 },
      { userId: "u5", userName: "Yusuf Salem", usedAt: new Date("2025-01-15"), orderAmount: 85 },
    ],
    totalRevenue: 1400,
    createdAt: new Date("2024-12-20"),
  },
  {
    id: "3",
    code: "FREETRIAL7",
    type: "free_trial",
    value: 7,
    totalUses: 15,
    maxUses: 30,
    perCustomerLimit: 1,
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-03-01"),
    productIds: ["prod-3"],
    status: "active",
    usages: [],
    totalRevenue: 0,
    createdAt: new Date("2025-01-28"),
  },
  {
    id: "4",
    code: "BLACKFRIDAY50",
    type: "percentage",
    value: 50,
    totalUses: 200,
    maxUses: 200,
    perCustomerLimit: 1,
    startDate: new Date("2024-11-25"),
    endDate: new Date("2024-11-30"),
    productIds: "all",
    status: "expired",
    usages: [
      { userId: "u6", userName: "Layla Ahmad", usedAt: new Date("2024-11-25"), orderAmount: 100 },
      { userId: "u7", userName: "Khaled Mansour", usedAt: new Date("2024-11-26"), orderAmount: 150 },
      { userId: "u8", userName: "Nadia Farid", usedAt: new Date("2024-11-27"), orderAmount: 80 },
    ],
    totalRevenue: 10000,
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "5",
    code: "EARLYBIRD20",
    type: "percentage",
    value: 20,
    totalUses: 75,
    maxUses: 100,
    perCustomerLimit: 1,
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-10-15"),
    productIds: ["prod-1"],
    status: "expired",
    usages: [
      { userId: "u9", userName: "Rania Helmi", usedAt: new Date("2024-09-05"), orderAmount: 200 },
      { userId: "u10", userName: "Tariq Osman", usedAt: new Date("2024-09-10"), orderAmount: 180 },
    ],
    totalRevenue: 6000,
    createdAt: new Date("2024-08-25"),
  },
];

export const mockProducts = [
  { id: "prod-1", name: "Digital Marketing Masterclass" },
  { id: "prod-2", name: "Social Media Growth Guide" },
  { id: "prod-3", name: "Content Creation Bootcamp" },
  { id: "prod-4", name: "1-on-1 Coaching Session" },
];
